name: 3D Profile Contribution
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: Ayush-0918
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "generate 3D contribution profile"
          file_pattern: "profile-3d-contrib/*.svg"
